### ISSUE TITLE
I would love to contribute my codes for your DSA repository

### ISSUE THREAD

**Issue by Anmol-Prasad** [ayu8/DSA-4-All#1]
Hi ! I would like to contribute to your code. I have implemented stacks, queues and Binary Tree and other basic data structures in C++ and would be glad to share them for Hacktoberfest. Along with this I have also implemented other sorting and searching algorithms. Would be glad if you can assign this project to me as well. Hoping for a nice collab :)

**Comment by ayu8** [comment]
Sure Anmol. Everyone is welcome.
I will keep the repo ready by tonight (will update CONTRIBUTING.md) so that anyone can add files and contribute.
