### ISSUE TITLE
PowerOfTwo

### ISSUE THREAD

**Issue by Shiyadh123** [ayu8/DSA-4-All#11]
I would like to add the program to check if a number is a power of 2 or not in the bit manipulation folder.
Please assign this task to me @ayu8 .

**Comment by Shiyadh123** [comment]
Hi @Dipesh-007 , I will be giving an O(1) time solution.
Hope you are also thinking of the same solution using bit manipulation.

**Comment by ayu8** [comment]
@Dipesh-007 @Shiyadh123 
If the solutions are in different languages or have different approaches, i'll merge both.
Please go through the ```Note``` mentioned in the ```CONTRIBUTING.md```

**Comment by Tushar7890** [comment]
heyy i want to give optimized solution to this problem in O(1) using bitwise

**Comment by Tushar7890** [comment]
heyy i want to give optimized solution to this problem in O(1) using bitwise

**Comment by Tushar7890** [comment]
heyy i want to give optimized solution bit-manipulation folder to this problem  in O(1) using bitwise, please assign this issue to me @ayu8
