### ISSUE TITLE
Merge Two Sorted Lists.

### ISSUE THREAD

**Issue by Shiyadh123** [ayu8/DSA-4-All#12]
I would like to add the program to Merge Two Sorted Lists. in the Linked List folder.
Please assign this task to me @ayu8 .

**Comment by Shiyadh123** [comment]
Sure

**Comment by gaurav-iitb** [comment]
please assign this to me

**Comment by Mani628** [comment]
Hi @ayu. I am a newbie to this open source contest. I am looking forward to learn many new things. I am ready with the code. Can you plz assign me this. @gaurav-iitb Bro Can i help you with the code. I will provide documentation.

**Comment by ayu8** [comment]
Sure @Mani628 
Go ahead

**Comment by shrutimeg** [comment]
i  want to do this program and please assign me this program @ayu8 .

**Comment by ayu8** [comment]
Go ahead @shrutimeg 
Kindly go through the CONTRIBUTING.md once

**Comment by Akash-moon** [comment]
Hello @ayu8 sir, I want to contribute my efforts on this problem.
plz assign it to me under hacktoberfest22.

**Comment by ayu8** [comment]
> Hello @ayu8 sir, I want to contribute my efforts on this problem. plz assign it to me under hacktoberfest22.

Go ahead
