### ISSUE TITLE
 Sum of Root To Leaf Binary Numbers

### ISSUE THREAD

**Issue by 123shanawaz** [ayu8/DSA-4-All#128]
hey @ayu8 , I want to add this solution in CPP into the Binary Tree folder, please assign this to me and add this under hacktoberfest label

problem link:https://leetcode.com/problems/sum-of-root-to-leaf-binary-numbers/

**Comment by ayu8** [comment]
Go ahead
Make sure to go through [CONTRIBUTING.md](https://www.github.com/ayu8/DSA-4-ALL/blob/main/CONTRIBUTING.md/) once
