### ISSUE TITLE
Frog jump

### ISSUE THREAD

**Issue by 123shanawaz** [ayu8/DSA-4-All#130]
hey @ayu8  , I want to add this solution in CPP into the DP folder, please assign this to me and add this under hacktoberfest label

problem link:https://www.codingninjas.com/codestudio/problems/frog-jump_3621012

**Comment by ayu8** [comment]
Go ahead
Make sure to go through [CONTRIBUTING.md](https://www.github.com/ayu8/DSA-4-ALL/blob/main/CONTRIBUTING.md/) once
