### ISSUE TITLE
Lowest Common ancestor of a binary tree

### ISSUE THREAD

**Issue by PIYUSH-MISHRA-00** [ayu8/DSA-4-All#132]
Hey @ayu8 i want to add this solution in the binary tree folder. Please assign me this issue and mark this under hacktoberfest.

**Comment by ayu8** [comment]
Go ahead
Make sure to go through [CONTRIBUTING.md](https://www.github.com/ayu8/DSA-4-ALL/blob/main/CONTRIBUTING.md/) once
