### ISSUE TITLE
House robber 2

### ISSUE THREAD

**Issue by 123shanawaz** [ayu8/DSA-4-All#147]
hey @ayu8, I want to add this solution in CPP into the DP folder, please assign this to me and add this under hacktoberfest label

**Comment by Akash-moon** [comment]
Hello @ayu8 sir, I want to contribute my efforts on this problem.
plz assign it to me under hacktoberfest22.

**Comment by ayu8** [comment]
@Akash-moon 
Please find some other issue
@123shanawaz is already doing this

**Comment by 123shanawaz** [comment]
@ayu8 @Akash-moon yes I am doing this......

**Comment by Akash-moon** [comment]
Ok Np @123shanawaz @ayu8 .
