### ISSUE TITLE
Median of 2 sorted arrays

### ISSUE THREAD

**Issue by CS50X-RGB** [ayu8/DSA-4-All#185]
hey @ayu8, I want to add this solution in CPP into the Array folder, please assign this to me and add this under hacktoberfest label

**Comment by ayu8** [comment]
Ok go for it.
Make sure you go through [CONTRIBUTING.md](https://www.github.com/ayu8/DSA-4-ALL/blob/main/CONTRIBUTING.md) before and do follow the rules.

**Comment by oops-aman** [comment]
i have solved this problem in cpp on LeetCode. Please assign to me

**Comment by oops-aman** [comment]
I have made a PR. Please check it out.

**Comment by CS50X-RGB** [comment]
But you didn't get the issue assigned

**Comment by CS50X-RGB** [comment]
And i have also the solution with me
