### ISSUE TITLE
Graph Folder, BFS and DFS in C++

### ISSUE THREAD

**Issue by Shiyadh123** [ayu8/DSA-4-All#27]
I would like to add a graph folder and programs for BFS and DFS traversal in it.
Please assign this task to me @ayu8 .

**Comment by ayu8** [comment]
I'd request you to read CONTRIBUTING.md once

I have mentioned that:

- Only add solutions to the questions which are on any coding platform, with the link to that question.
- No need to add driver-code for the problem or the main() function.
- File should contain the solution code as well as the link to that question (as comment in the code).
- The name of the file should follow snake_case convention.
- Create file under appropriate folder (topic).
