### ISSUE TITLE
BINARY TREE PATH

### ISSUE THREAD

**Issue by Sohanlalkush** [ayu8/DSA-4-All#78]
Hey @ayu8 i want to add this solution in Binary tree folder, pls assign me this and add this under hacktoberfest label

**Comment by ayu8** [comment]
Make sure you read `CONTRIBUTING.md` once

**Comment by ayu8** [comment]
> Hi @ayu8 . I am a newbie to this open source contest. I am looking forward to learn many new things. I am ready with the code. Can you plz assign me this. @Sohanlalkush Bro Can i help you with the code. I will provide documentation.

Hey, this issue has been closed. You can try and check some other open issues
