### ISSUE TITLE
PATH SUM

### ISSUE THREAD

**Issue by Sohanlalkush** [ayu8/DSA-4-All#79]
Hey @ayu8 i want to add this solution in Binary tree folder, pls assign me this and add this under hacktoberfest label

**Comment by ayu8** [comment]
Are you going to work on https://leetcode.com/problems/minimum-path-sum/ ?

This has been already assigned

**Comment by ayu8** [comment]
Go ahead !
Make sure to go through [`CONTRIBUTING.md`](https://github.com/ayu8/DSA-4-All/blob/main/CONTRIBUTING.md) once

**Comment by Mani628** [comment]
I have solution to this problem. Can i contribute ?? Plz assign me this under hacktober fest 22
Plz @ayu8 
@Sohanlalkush Bro Can I help you with the code ??
