### ISSUE TITLE
Smallest string starting from leaf

### ISSUE THREAD

**Issue by Sohanlalkush** [ayu8/DSA-4-All#81]
Hey @ayu8 i want to add this solution in Binary tree folder, pls assign me this and add this under hacktoberfest label

**Comment by Mani628** [comment]
Hi @ayu. I am a newbie to this open source contest. I am looking forward to learn many new things. I am ready with the code. Can you plz assign me this under label"hacktoberfest22" . @Sohanlalkush  Bro Can i help you with the code. I will provide documentation.
