### ISSUE TITLE
Reverse Bits

### ISSUE THREAD

**Issue by Amarendra-ai** [ayu8/DSA-4-All#93]
Hey @ayu8, I want to add this solution in CPP into the bit-manipilation folder, please assign this to me and add this under hacktoberfest label

Problem link: https://leetcode.com/problems/reverse-bits/description/

**Comment by Mani628** [comment]
Hi @ayu. I am a newbie to this open source contest. I am looking forward to learn many new things. I am ready with the code. Can you plz assign me this under label"hacktoberfest22" . @Sohanlalkush  Bro Can i help you with the code. I will provide documentation.

**Comment by ayu8** [comment]
Go ahead @Mani628
