### ISSUE TITLE
Hamming Distance 

### ISSUE THREAD

**Issue by Amarendra-ai** [ayu8/DSA-4-All#94]
Hey @ayu8, I want to add this solution in CPP into the bit-manipilation folder, please assign this to me and add this under hacktoberfest label

Problem link: https://leetcode.com/problems/hamming-distance/description/

**Comment by ayu8** [comment]
Please go through the [CONTRIBUTING.md](https://www.github.com/ayu8/DSA-4-ALL/blob/main/CONTRIBUTING.md) once
